name: TUN
favicon: null
layout_spectrum: 0.98916
typography_spectrum: 0.27539
title: Thoughts and Feelings on Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303038'
    - '#dbdee7'
    - '#c25e60'
    - '#5f7394'
    - '#e0a85d'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
