name: TUN
favicon: null
layout_spectrum: 0.98916
typography_spectrum: 0.27539
title: Thoughts and Feelings on Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7ec9ff'
    - '#17141b'
    - '#a58b74'
    - '#faab82'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
