name: tun
favicon: null
layout_spectrum: 0.08456211816519499
typography_spectrum: 0.616846926510334
title: Thoughts and Feelings on Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#303038'
    - '#dbdee7'
    - '#c25e60'
    - '#5f7394'
    - '#e0a85d'
  brandStrength: 0.6875
  lightness: 0.5749187208712101
  saturation: 0.7055542939342558
  rhythmicContrast: 0.25
purpose: []
